### ISSUE TITLE
New compact graffitiwall format not returned by API

### ISSUE THREAD

**Issue by benv666** [gobitfly/eth2-beaconchain-explorer#1194]
The graffitiwall API at https://beaconcha.in/api/v1/graffitiwall does not seem to be returning a new compact style graffitiwall format.
When searching for gw: like [this](https://beaconcha.in/blocks?q=gw%3A) you see [one block returned at slot 2885406](https://beaconcha.in/block/2885406) that my discord bot parsed as a pixel at x:649, y: 471 and color #FF9C68 by validator 277159 , but when I reloaded the graffitiwall it did not get returned in the graffitiwall API call.

```
$ curl -s https://beaconcha.in/api/v1/graffitiwall | grep 2885406
$
```

In addition, checking the graffitiwall image at https://beaconcha.in/graffitiwall with a graphics editor it seems that the pixel hasn't been drawn either.
![beconwall](https://user-images.githubusercontent.com/165034/149739888-660923c3-8112-404c-9470-5b1bf7b9bbb6.png)

**Comment by InvisibleSymbol** [comment]
After testing it locally I can confirm that this is not caused by the new graffiti format logic itself.
![image](https://user-images.githubusercontent.com/34715248/151700473-4eb0b755-c3ed-4bea-a032-a434d4ee581c.png)
![image](https://user-images.githubusercontent.com/34715248/151700211-8e1b5b66-60ab-4cc2-bc27-0f24cb521c7c.png)
Since this issue has been opened there also has been 2 new proposals using the compact format, both showing up at the api endpoint.
![image](https://user-images.githubusercontent.com/34715248/151700947-183af937-15e1-4360-a877-80fd8aa07f64.png)
![image](https://user-images.githubusercontent.com/34715248/151700983-7d7d6991-77c9-4a2d-abea-f66d1da48ab9.png)
My current assumptions are that either something else cause that slot to break (which i can't test, because i only have a testnet instance) or that there somehow was a temporary db failure, which would cause the addition to silently fail.

**Comment by InvisibleBitfly** [comment]
has been working fine ever since. prob have to re-export all the graffiti one day to ensure everything is correct.
