### ISSUE TITLE
Incorrect numbers

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#144]
1. pending validators (https://beaconcha.in/ shows 0)

2. wrong average balance https://altona.beaconcha.in/
 only one validator has more than 32.06 ETH but average shows .09

![image](https://user-images.githubusercontent.com/26490734/86096262-579c6100-bab3-11ea-822b-4b289a7b7fed.png)
![image](https://user-images.githubusercontent.com/26490734/86096137-30459400-bab3-11ea-828d-61c9e5d84cb8.png)

3. Average Daily income chart & Staking rewards chart incorrect

**Comment by guybrush** [comment]
1. This bug is due to an already fixed bug in the prysm-api (https://github.com/prysmaticlabs/prysm/issues/6416) - only the onyx-explorer is affected by this. Will update the data in the background (will take some time).
2. Right now it looks like the numbers are correct? Also in the screenshot all the validators have > 32.2 ETH. The average is 32.09 because there are others with lower balance.

**Comment by Buttaa** [comment]
Average balance seems to be fixed, pending validator bug remains
