### ISSUE TITLE
Make "balance decrease" alert less sensible

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#188]
Attestations can be positive but still return a negative reward. 

1. 

Danny Ryan:
> 3 of them can be positive or negative (source, target, head)
> 1 can be just positive (inclusion delay)
> You have to get at least source correct to be included
> so the lowest inclusion delay reward is like 1/32 of a base reward (near zero)
> So it'd be base_reward - 2 * base_reward + base_reward / 32)
> so max reward is 4 * base_reward
> so if we just assume base_reward / 32 is 0
> then the above is - base_reward
> and as a fraction of the max
> it's - base_reward / (4 * base_reward)
> or **-1 / 4**

A positive attestation with a negative reward of **-26% (of maximum attestation reward)** should not cause an alert. 

2. 

Additionally to make balance alerts less spammy we could do the following... 

balance decrease from Epoch N to Epoch n+1 triggers the alert, if the balance for n+2 , n+3 ... decreases as well do not send another alert. Reset the alert if the balance has incereased for at least one or two epochs.

**Comment by MysticRyuujin** [comment]
I would prefer to be spammed if there was a real issue, I feel like the first fix is much better than the second...

**Comment by MysticRyuujin** [comment]
Maybe slightly better might be to alert only if your balance decrases 2 epochs in a row?

**Comment by guybrush** [comment]
Right now the system sends an alert if the subscribed validator's balance decreases for 3 consecutive epochs. It will only send another alert regarding this validator once its balance increases again for at least 1 epoch.

**Comment by torfbolt** [comment]
During this period of Medalla non-finality, the current alert feature is not really useful. I would highly appreciate having an alert only when my validator misses attestations, or alternatively an (adjustable?) threshold to discern between late-attestation-leaking and quadratic-leaking during non-finality.

IMO false positives are problematic too, in my case they led to me not noticing for 3 days that my Medalla validator had dropped out.

Maybe there could be an additional alert option "attestations missed", which does not monitor balances but instead time since last attestation?
