### ISSUE TITLE
Inclusion distance different to eth2 spec

### ISSUE THREAD

**Issue by torfbolt** [gobitfly/eth2-beaconchain-explorer#196]
The currently displayed "inclusion distance" values are calculated as the delay with respect to the earliest possible inclusion due to missed slots. This differs from the eth2 spec definition, where it is just `inclusion_slot_number` - `attestation_slot_number`.

There are different options here:

- Keep it as is, with the risk of confusing users that expect to see the eth2 spec value that is used to calculate attestation rewards
- Change it to the eth2 spec definition, with the risk of confusing users that expect to see a constant value for an optimally performing validator
- Make it selectable (e.g. checkbox with clear naming and tooltip describing the differences), with the risk of cluttering the UI
- Switch randomly between both definitions every time the user hits reload ;)

If the first option is preferred, I would propose to at least name it differently to avoid confusion.

**Comment by yorickdowne** [comment]
During non-finality spadina, this confused me. I saw inclusion at perfect 0 and no misses, and yet my balance was ever so slowly draining.

Of course if the distance is larger because there are missed blocks, then it makes sense I am seeing a small drain.

I vote for "selectable", in settings somewhere. Not a straight up toggle on the page, just a setting an advanced user can choose.

**Comment by guybrush** [comment]
Current state:

![optimal_inclusion_distance](https://user-images.githubusercontent.com/306324/98934875-02517100-24e3-11eb-996a-04faf018976d.jpg)

I think the "optimal inclusion distance" is more relevant for the validator-owner, since it shows that the validator could do better (the network would allow for a better performance).

**Comment by torfbolt** [comment]
As @yorickdowne mentioned, this depends heavily on the use-case. If you want to find inclusion distance problems of your client software during times of a healthy network, I agree that the current display is good. If you want to research the rewards or penalties your validator is getting (which are calculated by the spec definition of inclusion distance), I would argue that showing the other one is better. Especially in times when the network is struggling and the earliest available slot is not just the next one.

So I would also argue for selectable, as both of these are relevant use-cases for a block explorer IMO.

**Comment by guybrush** [comment]
We could also do `<inclusionDistance>`/`<optimalInclusionDistance>` (separated by /)
