### ISSUE TITLE
API endpoints for proposals and withdrawals not returning data

### ISSUE THREAD

**Issue by rambowtech** [gobitfly/eth2-beaconchain-explorer#2168]
The following API endpoints return an empty data field:

/api/v1/validator/{indexOrPubkey}/proposals

/api/v1/validator/{indexOrPubkey}/withdrawals

**Comment by recy21** [comment]
Thank you for your interest in our project.

https://beaconcha.in/api/v1/validator/203030/proposals works as expected.
It will not work with random validators, because they likely did not propose a block in the last 100 epochs.

**Description of the endpoint:** Get all proposed blocks during the last 100 epochs for up to 100 validators. Optionally set the epoch query parameter to look back further.

So the endpoint works correctly, but it's only returning results for the last 100 epochs, which is a bad design, we know that and will be improved with the v2 API, we are working currently on!

Meanwhile I can recommend the https://beaconcha.in/api/v1/execution/203030/produced endpoint, but it's only returning post-merge blocks. Maybe that's enough for you till v2 is ready?

**Comment by rambowtech** [comment]
I see, thanks for the response. Looking forward to v2 then...

**Comment by recy21** [comment]
soon :)
