### ISSUE TITLE
Most Recent Blocks -> View More, missed slots aren't present

### ISSUE THREAD

**Issue by xanatos** [gobitfly/eth2-beaconchain-explorer#2206]
There was a little problem with missed slots today, and while watching your site I noticed that while in the Most Recent Blocks pane in the home page the missed slots were visible (and marked orange), if I went to the View More, the missed slots didn't get a row:

![image](https://github.com/gobitfly/eth2-beaconchain-explorer/assets/821344/d715bb7f-3bb4-4772-b90f-9849665969f7)

**Comment by recy21** [comment]
Thank you for your interest in our project.

Each block has a slot, but not all slots have a block.
We show missed blocks on the home page, because it is a live ticker. But on the list of blocks (after you click on "VIew more") only the created blocks will be shown. This is by design. (Sorry for the confusion, I can understand why).
