### ISSUE TITLE
how run on localhost

### ISSUE THREAD

**Issue by avenbreaks** [gobitfly/eth2-beaconchain-explorer#2278]
hi, we are building a blockchain fork of ethereum beacon, I am using EL geth, erigon and lighthouse as CL. but how can we run beacon explorer for our project? is there any special documentation step by step running beacon explorer and using bigtable? Thank You

**Comment by Buttaa** [comment]
> hi, we are building a blockchain fork of ethereum beacon, I am using EL geth, erigon and lighthouse as CL. but how can we run beacon explorer for our project? is there any special documentation step by step running beacon explorer and using bigtable? Thank You

@avenbreaks , I apologize for the inconvenience, but we no longer provide step-by-step documentation _[for now]_ for running the explorer. However, if you provide more details about your project, we can explore possible solutions together.
Feel free to join our [Discord community ](https://discord.io/beaconchain)

**Comment by recy21** [comment]
Thank you for your interest in our project.

Did you already checked: https://github.com/gobitfly/eth2-beaconchain-explorer#readme ?

There is also https://github.com/gobitfly/eth-explorer-workshop-bogota , but the info there might be outdated, as there were a lot of changes since the last update.

But as the Explorer itself is currently under high development, there is simply no time for updating all related repositories and/or keeping the documentation up to date. So the answer to your question is: currently there is no step by step documentation which covers everything in detail.
We will try our best to catch up after the explorer has all its new features ready, but I would suggest to use an older version of the explorer meanwhile (where the Bogota workshop documentation is still working).
