### ISSUE TITLE
error calling getExecutionChartData: context deadline exceeded

### ISSUE THREAD

**Issue by cppfuns** [gobitfly/eth2-beaconchain-explorer#2290]
Many Bigtable queries in the query logic will time out. How to solve this situation?

https://github.com/gobitfly/eth2-beaconchain-explorer/blob/7c5e032b2db113df47f83a7a043ae0efe3fe1c32/db/bigtable_eth1.go#L472

```
func (bigtable *Bigtable) GetBlocksIndexedMultiple(blockNumbers []uint64, limit uint64) ([]*types.Eth1BlockIndexed, error) {
	rowList := gcp_bigtable.RowList{}
	for _, block := range blockNumbers {
		rowList = append(rowList, fmt.Sprintf("%s:B:%s", bigtable.chainId, reversedPaddedBlockNumber(block)))
	}

	ctx, cancel := context.WithDeadline(context.Background(), time.Now().Add(time.Second*30)) // Even if I change to 60 seconds, it will time out
	defer cancel()

```

how to solve this problem?

**Comment by Buttaa** [comment]
Hey @cppfuns ,

Thanks for raising the issue. Unfortunately, we don't provide technical support for the project. If your project aligns with the Ethereum ethos and you're interested in an EaaS (Explorer as a Service), feel free to reach out to us on [Discord](https://discord.io/beaconchain).

**Comment by cppfuns** [comment]
> Hey @cppfuns ,
> 
> Thanks for raising the issue. Unfortunately, we don't provide technical support for the project. If your project aligns with the Ethereum ethos and you're interested in an EaaS (Explorer as a Service), feel free to reach out to us on [Discord](https://discord.io/beaconchain).

For an open source project, are you unwilling to answer such basic questions? The problems you encounter from use are not worth improving for the project?

**Comment by cppfuns** [comment]
@recy21 Do you have a different opinion?

**Comment by recy21** [comment]
@cppfuns I have the current version up and running and all queries are running fine. There are sometimes (about twice a day) some timeouts, I already contacted Google (I host my bigtable directly there) about it, it seems they can't explain the spikes either, but we are investigating the problem and may post it here if we find a solution.

Your problem on the other hand does not sound similar to mine. It looks more like your bigtables have a fundamental problem, because if I understand you correctly, they are "always" interrupted? There could be several reasons for this: Too few resources, too many queries at the same time, some other random thing with your setup (I can't think of anything).

Unfortunately Butta is right, we don't offer technical support (currently), and I can only help you with this information: "It works on at least 3 other installations, without your problem, so the problem is not in the code, but in your setup" + "Try to trace / debug the queries separate one by one, which might give a hint on the issue"

I'm sorry that I can't help you any further.

**Comment by cppfuns** [comment]
@Buttaa @recy21 Thank you both, I wish you all the best
