### ISSUE TITLE
Attestation inconsistency

### ISSUE THREAD

**Issue by mariavarvaroi** [gobitfly/eth2-beaconchain-explorer#2950]
**Describe the bug**
Attestations show as `missed` in the `Validator History` panel, but signed with a delay in the attestations panel

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to one of these validators: [201585](https://beaconcha.in/validator/201585), [202553](https://beaconcha.in/validator/202553) , [201562](https://beaconcha.in/validator/201562) (and others). The attestation for epoch 308652 shows as missed in the `Validator History`, but successful with a delay in the left panel. 

**Expected behavior**
The information in both panels should be consistent

**Screenshots**
![Screenshot 2024-09-03 at 08 43 45](https://github.com/user-attachments/assets/ea8aa722-1d30-408e-8761-4bd568f59857)

![Screenshot 2024-09-03 at 08 43 16](https://github.com/user-attachments/assets/ebdb618b-afe0-4b49-bc7f-0bcd8a11cd36)

**Desktop (please complete the following information):**
Not relevant

**Additional context**
I am not sure this is a bug. The info in the `Validator History` is consistent with the `rewards` endpoint. I'm interested to understand what is the cause of this inconsistency. Can provide more validators with the same issue.

**Comment by invis-bitfly** [comment]
In this scenario, the attestation was included on-chain but didn't benefit the validator in any way – no rewards were earned, and full penalties were applied.

Here’s the specific breakdown of what had to happen for this to occur:
- The attestation was included after more than one slot, so no head reward.
- The target hash voted for was wrong, so no target reward.
- The attestation was included after more than five slots, so no source reward.
- The attestation was valid as the source hash was correct.

This edge case occurred because the attestation was not included earlier by proposers, likely due to the head and target hash being incorrect, leading to its de-prioritization. So, while the validator technically attested, it was basically the same as not attesting at all.

The rewards history marks this as "missed" since all possible rewards were negative or zero. This is a bit of a bug and will be better explained in the UI in v2.

For more details, refer to the [Ethereum Consensus Specs](https://github.com/ethereum/consensus-specs/blob/aa3b1401974772b9f6f21a7e80273cbaf0288318/specs/altair/beacon-chain.md#get_attestation_participation_flag_indices).

**Comment by mariavarvaroi** [comment]
Thanks a lot, this is very helpful!

**Comment by mariavarvaroi** [comment]
Thanks a lot, this is very helpful!
