### ISSUE TITLE
Low default block count on "blocks" page on initial load

### ISSUE THREAD

**Issue by arnetheduck** [gobitfly/eth2-beaconchain-explorer#457]
When loading the "Blocks" page, by default 10 blocks are shown, most of them "scheduled" - the first thing I do every time is to increase the blocks-per-page limit - a useful minimum would be 1 epoch to ensure that at least one proposed block is visible. Also, given that scheduling is known an epoch in advance, it might make sense to show it "earlier" - as a small nitpick, the front page shows more block which makes clicking the "view more" button funny.

**Comment by protolambda** [comment]
The block proposers are not fully known one epoch in advance. It is not the same as with committees.

E.g. a proposer of the next epoch is known, but its balances changes drastically during the epoch transition before that epoch. It may then not be selected due to the balances being part of the selection process.

Agree though that any known set of proposers of the current epoch would be nice to show by default.

**Comment by Buttaa** [comment]
Thanks, this was solved a long time ago. Please re-open if the issue persists :)
