### ISSUE TITLE
Android app: no connection, login fails

### ISSUE THREAD

**Issue by rambowtech** [gobitfly/eth2-beaconchain-explorer#955]
Samsung Galaxy Note 9, Android 10

I got a no connection error on the dashboard. Logout and then login again fails. I get to the point where you confirm "Do you want to link your account with Beaconchain Dashboard?", upon confirming it quits with the message that login failed and I should try again later.
Force closing, restarting, deleting data, reinstalling did not help.

Problem occurred previously and some time after reinstalling (but not immediately) it randomly worked again for a while.

**Comment by rambowtech** [comment]
2.2.3
Yes
Interesting. I tried again over 4G and it worked. Logged out again and tried to login via WiFi and it failed again.

**Comment by manuelsc** [comment]
You might be using the old machine metrics collection endpoint. Head over to the beaconcha.in website, head over to settings -> mobile app and check if the displayed URL is the same as in your config on your staking setup. If not, switch to the new URL. The reason is that the old endpoint might cause you to run into a rate limit based on your IP address. Changing the url should resolve this (might take a while in WLAN for your IP rate limit to recover, we will look into a way of fixing this).

**Comment by rambowtech** [comment]
The endpoints did indeed differ. I changed it to the new one. Thanks.

**Comment by rambowtech** [comment]
By the way, I just saw that I now have an additional paired device in the list on the website for every failed attempt.

**Comment by manuelsc** [comment]
Yeah sorry about that, we messed up the communication part of switching to the new URL. It should fix your problems. DM me or butta or write us an email for a free month of premium for your troubles.  

Thanks for letting us know, we are aware of the multiple devices and will address this in a future update.

**Comment by rambowtech** [comment]
No worries. Thanks for helping out quickly. You might want to consider a feature for easy submission of feedback/bugs. Not everybody has GitHub account or wishes to create one. Keep up the the good work.
